### ISSUE TITLE
[Feature Request] One-click Copy PID to clipboard

### ISSUE THREAD

**Issue by eficker** [fishnetsecurity/Lair#56]
Add a javascript button (and perhaps associated hotkey) that copies the current PID to the system clipboard.

The double-click highlight gets more than you want (at least in chrome) and slow-drag highlighting, is well, a drag.

**Comment by tomsteele** [comment]
I think double-clicking is fixed. The only solution to affect the clipboard is with flash. If you know of something else, please re-open and we'd be happy to investigate. Thanks :)
