### ISSUE TITLE
scan file upload via web

### ISSUE THREAD

**Issue by WebBreacher** [fishnetsecurity/Lair#60]
To better support distributed testing, please consider allowing remote users with valid usernames/passwords to the web app to upload nmap|nessus|nexpose scans via the web UI. Currently, as I understand it, a remote user would need to have access to the backend mongo db and have the drone send content directly to it. With people doing testing together in different cities/states, this access to mongo db for lair may not be feasible.

**Comment by tomsteele** [comment]
Going to close this as we have a supported solution, next release may have this in the build. Thanks.

**Comment by WebBreacher** [comment]
Cool. Sounds good!
